#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
room_domain=$(ynh_app_setting_get $app room_domain)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP THE METRONOME CONFIG
#=================================================

ynh_backup "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

#=================================================
# BACKUP THE METRONOME DATAS
#=================================================

# Convert the domain of the chatroom like the name of the directory for metronome.
metronome_domain_dir=${room_domain//-/%2d}
metronome_domain_dir=${metronome_domain_dir//./%2e}
metronome_domain_dir=${metronome_domain_dir//_/%5f}

ynh_backup "/var/lib/metronome/$metronome_domain_dir"
