#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
room_domain=$YNH_APP_ARG_ROOM_DOMAIN
path_url=/

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path_url)

# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app room_domain $room_domain

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_replace_string "__ROOM_DOMAIN__" "$room_domain" "../conf/nginx.conf"
# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# CONFIGURE METRONOME
#=================================================

# Add the muc_log module for logging
echo "

-- Discovery items
disco_items = {
    { \"$room_domain\" }
};

---Set up a MUC (multi-user chat) room server
Component \"$room_domain\" \"muc\"
    name = \"YunoHost Chatrooms\"

    modules_enabled = {
        --\"muc_limits\";
        \"muc_log\";
        \"muc_log_http\";
        \"pastebin\";
    }

    muc_event_rate = 0.5
    muc_burst_factor = 10

    muc_log_http_config = {
        url_base = \"logs\";
        theme = \"metronome\";
    }

    pastebin_url = \"http://$domain/paste/\"
    pastebin_path = \"/paste/\"
    pastebin_expire_after = 0
    pastebin_trigger = \"!paste\"" \
	>> "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

chmod 640 "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"
chown metronome: "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

# Convert the domain of the chatroom like the name of the directory for metronome.
metronome_domain_dir=${room_domain//-/%2d}
metronome_domain_dir=${metronome_domain_dir//./%2e}
metronome_domain_dir=${metronome_domain_dir//_/%5f}

# Create the directory for the rooms configs
mkdir -p "/var/lib/metronome/$metronome_domain_dir"

# Set the rooms as persistent
# echo "return {
#         [\"apps@$room_domain\"] = true;
#         [\"dev@$room_domain\"] = true;
#         [\"support@$room_domain\"] = true;
# };" >> "/var/lib/metronome/$metronome_domain_dir/persistent.dat"

# Configure each room
# conf_room () {
# 	echo "return {
#         [\"jid\"] = \"$1@$room_domain\";
#         [\"_data\"] = {
#                 [\"history_length\"] = 20;
#                 [\"logging\"] = true;
#                 [\"persistent\"] = true;
#                 [\"whois\"] = \"moderators\";
#         };
#         ["_affiliations"] = {};
# };" >> "/var/lib/metronome/$metronome_domain_dir/config/$1.dat"
# }

# conf_room apps
# conf_room dev
# conf_room support

# Set correct permissions on metronome files
chown metronome: -R "/var/lib/metronome/$metronome_domain_dir"
# chmod 640 "/var/lib/metronome/$metronome_domain_dir/persistent.dat"
# chmod 750 "/var/lib/metronome/$metronome_domain_dir/config"
# chmod 640 /var/lib/metronome/$metronome_domain_dir/config/{apps.dat,dev.dat,support.dat}

# For the moment, this test to force the config of each rooms doesn't work.
# Metronome seems to be not so happy with that...
# So, we have to configure each room manually.
echo "To enable the logging in $domain, each room have to be configured." >&2
echo "You can configure a room by entre '/config' in a room." >&2
echo "Then, you have to set the room as persistent and enable the logging." >&2
echo "--" >&2
echo "You can also set this config in the file of the room." >&2
echo "The config files are at '/var/lib/metronome/$metronome_domain_dir/config/'" >&2
echo "Add '[\"logging\"] = true;' and '[\"persistent\"] = true;' in the '_data' array." >&2
echo "Then restart metronome." >&2

#=================================================
# ADD THE DOMAIN /ETC/HOSTS
#=================================================

echo "
127.0.0.1	$room_domain" >> /etc/hosts

#=================================================
# RESTART METRONOME
#=================================================

systemctl restart metronome

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_set $app unprotected_uris "/"

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
