#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
room_domain=$(ynh_app_setting_get $app room_domain)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE CRON FILE
#=================================================

ynh_secure_remove "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

#=================================================
# CLEAN /ETC/HOSTS
#=================================================

sed -i "/127.0.0.1.*$room_domain/d" /etc/hosts

#=================================================
# RESTART METRONOME
#=================================================

systemctl restart metronome
