#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
room_domain=$(ynh_app_setting_get $app room_domain)
path_url=$(ynh_app_setting_get $app path)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_webpath_available $domain $path_url \
	|| ynh_die "Path not available: ${domain}${path_url}"

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# RESTORE THE METRONOME CONFIG
#=================================================

ynh_restore_file "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

#=================================================
# RESTORE THE METRONOME DATAS
#=================================================

# Convert the domain of the chatroom like the name of the directory for metronome.
metronome_domain_dir=${room_domain//-/%2d}
metronome_domain_dir=${metronome_domain_dir//./%2e}
metronome_domain_dir=${metronome_domain_dir//_/%5f}

ynh_restore_file "/var/lib/metronome/$metronome_domain_dir"

#=================================================
# SET PERMISSIONS
#=================================================

chown metronome: "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"
chown metronome: -R "/var/lib/metronome/$metronome_domain_dir"

#=================================================
# ADD THE DOMAIN /ETC/HOSTS
#=================================================

echo "
127.0.0.1	$room_domain" >> /etc/hosts

#=================================================
# RESTART METRONOME
#=================================================

systemctl restart metronome

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
