#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
room_domain=$(ynh_app_setting_get $app room_domain)
path_url=$(ynh_app_setting_get $app path)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# CHECK THE PATH
#=================================================

# Normalize the URL path syntax
path_url=$(ynh_normalize_url_path $path_url)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_replace_string "__ROOM_DOMAIN__" "$room_domain" "../conf/nginx.conf"
# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# CONFIGURE METRONOME
#=================================================

# Verify the checksum and backup the file if it's different
ynh_backup_if_checksum_is_different "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

# Add the muc_log module for logging
echo "

-- Discovery items
disco_items = {
    { \"$room_domain\" }
};

---Set up a MUC (multi-user chat) room server
Component \"$room_domain\" \"muc\"
    name = \"YunoHost Chatrooms\"

    modules_enabled = {
        --\"muc_limits\";
        \"muc_log\";
        \"muc_log_http\";
        \"pastebin\";
    }

    muc_event_rate = 0.5
    muc_burst_factor = 10

    muc_log_http_config = {
        url_base = \"logs\";
        theme = \"metronome\";
    }

    pastebin_url = \"http://$domain/paste/\"
    pastebin_path = \"/paste/\"
    pastebin_expire_after = 0
    pastebin_trigger = \"!paste\"" \
	>> "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

chmod 640 "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"
chown metronome: "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

# Recalculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/metronome/conf.d/logging_$room_domain.cfg.lua"

#=================================================
# RESTART METRONOME
#=================================================

systemctl restart metronome

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_set $app unprotected_uris "/"

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
